### ISSUE TITLE
caf-logging-tomcat-juli-5.0.0-SNAPSHOT.jar missing org.apache.juli.AsyncFileHandler

### ISSUE THREAD

**Issue by dhsmith1001** [caf-archive/opensuse-tomcat-image#28]
The caf-logging-tomcat-juli/pom.xml includes a small subset of classes from tomcat-juli.jar. It doesn't include org.apache.juli.AsyncFileHandler which is used by IG, causing ClassNotFoundException when IG is deployed on opensuse-tomcat-image.

**Comment by dermot-hardy** [comment]
[SCMOD-9686](https://portal.digitalsafe.net/browse/SCMOD-9686) raised to track this on Jira.

**Comment by hoshposh** [comment]
Within the `caf-logging-tomcat-juli/pom.xml` file it seems that the following additional inclusions are needed for our application to proceed with startup using the `opensuse-tomcat-image`.

```xml
        <include>org/apache/juli/FileHandler**</include>
        <include>org/apache/juli/AsyncFile**</include>
```

**Comment by michael-bryson** [comment]
@hoshposh Could you submit this change in a PR and assign it to @rahul-kulkarni73 for review?

**Comment by rahul-kulkarni73** [comment]
Closed SCMOD-9686. Release notes are updated with the details.

**Comment by michael-bryson** [comment]
The PR to fix this issue has been accepted and merged. If you pull the latest 5.0.0-SNAPSHOT it will contain the changes.

**Comment by dermot-hardy** [comment]
@hoshposh @dhsmith1001
Hi guys,

Let us know if this fixes the issue.

Because this hasn't been released yet you need to pull it from the prereleases repository.

    docker login dockerhub-private.svsartifactory.swinfra.net
    docker image pull dockerhub-private.svsartifactory.swinfra.net/cafinternal/prereleases:opensuse-tomcat-5.0.0-SNAPSHOT

- Obviously you only need to login if you haven't already done so in the past.
- You can login with either SWINFRA domain or CORPDOM domain credentials.
  - To use SWINFRA credentials use your swinfra logon name as the username
(i.e. `hardyde` for me)
  - To use CORPDOM credentials use the full corpdom user principal name as the username
(i.e. `dermot.hardy@microfocus.com` for me)

Thanks,
Dermot

**Comment by hoshposh** [comment]
@dermot-hardy 

I verified that this fixes our issue using the pre-release artifact.

Cheers,
-Lyndon
